[env:esp32-c3-devkitc-02]
platform = espressif32@7.1.3
board = esp32-c3-devkitc-02
framework = arduino

monitor_speed = 115200
monitor_port = rfc2217://localhost:4000
monitor_echo = yes
monitor_eol = LF
monitor_filters = send_on_enter

lib_deps =
    madhephaestus/ESP32Servo@3.2.1
