[platformio]
default_envs = wokwi

[env]
platform = espressif32@7.1.3
framework = arduino
monitor_speed = 115200

lib_deps =
    madhephaestus/ESP32Servo@3.2.1

; ======================================================
; WOKWI SIMULATION
; ======================================================

[env:wokwi]
board = esp32-c3-devkitm-1

; Optional external serial monitor for the simulator.
; The built-in Wokwi terminal is the recommended workshop workflow.
monitor_port = rfc2217://localhost:4000
monitor_echo = yes
monitor_eol = LF
monitor_filters = send_on_enter

; ======================================================
; PHYSICAL ROBOT
; ======================================================

[env:physical]
board = esp32-c3-devkitc-02
